### ISSUE TITLE
The preview panel on the right always scroll up when typing.

### ISSUE THREAD

**Issue by notalentgeek** [jamiemcg/Remarkable#61] opened 2016-10-06 11:19 UTC
Annoying bug. When I type something, the preview panel always scrolled to the most up part of the document. So, I cannot see what I am typing, especially when I type a document with vertically long image.

**Comment by jamiemcg** [comment] 2016-10-10 20:47
Duplicate of #25

**Closed by jamiemcg** 2016-10-10 20:47 UTC
