### ISSUE TITLE
remarkable does not start on fedora 25

### ISSUE THREAD

**Issue by statquant** [jamiemcg/Remarkable#183] opened 2017-07-22 09:57 UTC
I run a fedora 25 distro, I installed the rpm.
I run wayland, is it an issue ?
From the shell I get the following:

```
 statquant  ~  remarkable 
Traceback (most recent call last):
  File "/usr/bin/remarkable", line 65, in <module>
    import remarkable
  File "/usr/lib/python3/dist-packages/remarkable/__init__.py", line 30, in <module>
    from remarkable import RemarkableWindow
  File "/usr/lib/python3/dist-packages/remarkable/RemarkableWindow.py", line 27, in <module>
    gi.require_version('WebKit', '3.0')
  File "/usr/lib64/python3.5/site-packages/gi/__init__.py", line 122, in require_version
    (namespace, version))
ValueError: Namespace WebKit not available for version 3.0
```

**Comment by mlsmithjr** [comment] 2017-08-03 15:47
I'm having the same problem on a fresh install of Fedora 26 too.  Was working on my previous box.  I love this editor - gotta figure this out.

**Comment by mlsmithjr** [comment] 2017-08-03 16:05
Figured it out.  Just install webkitgtk3

`sudo dnf install webkitgtk3
`

**Comment by jayvdb** [comment] 2017-08-15 01:43
On Fedora Rawhide, I've installed all sorts of Python <-> WebKit packages, and nothing works.

I have a slightly different error
```
Traceback (most recent call last):
  File "/bin/remarkable", line 65, in <module>
    import remarkable
  File "/usr/lib/python3/dist-packages/remarkable/__init__.py", line 30, in <module>
    from remarkable import RemarkableWindow
  File "/usr/lib/python3/dist-packages/remarkable/RemarkableWindow.py", line 27, in <module>
    gi.require_version('WebKit', '3.0')
  File "/usr/lib64/python3.6/site-packages/gi/__init__.py", line 118, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace WebKit not available
```


```
$ rpm -qa | grep -i '^py.*webkit'
python3-qt5-webkit-5.9-6.fc27.x86_64
PyQt4-webkit-4.12.1-4.fc27.x86_64
pywebkitgtk-1.1.8-13.fc26.x86_64
python-qt5-webkit-5.9-6.fc27.x86_64
python3-PyQt4-webkit-4.12.1-4.fc27.x86_64
$ dnf search py*webkit
PyQt4-webkit.x86_64 : Python bindings for Qt4 Webkit
PyQt4-webkit.i686 : Python bindings for Qt4 Webkit
python-qt5-webkit.x86_64 : Python bindings for Qt5 Webkit
python3-qt5-webkit.x86_64 : Python3 bindings for Qt5 Webkit
python3-PyQt4-webkit.x86_64 : Python3 bindings for Qt4 Webkit
python3-PyQt4-webkit.i686 : Python3 bindings for Qt4 Webkit
```

**Comment by mbloms** [comment] 2017-11-26 16:49
Duplicate of #39

**Comment by samtuke** [comment] 2018-08-21 11:17
Still have the problem on Fedora 28

**Comment by ekuester** [comment] 2018-11-26 18:01
@samtuke 
please install from [rpm-sphere](https://fedora.pkgs.org/28/rpm-sphere/remarkable-1.87-6.1.noarch.rpm.html), works without problems ... perhaps additionally have a look at my issue #282.

**Closed** 2024-09-22 19:57 UTC
