### ISSUE TITLE
Fedora 26: "webkitgtk3" should be a dependency in rpm

### ISSUE THREAD

**Issue by gtk-aschmidt** [jamiemcg/Remarkable#193] opened 2017-08-31 16:30 UTC
After installing the .rpm file from [github.io](https://remarkableapp.github.io/linux/download.html) I found that launching the application produced the error:

```
  File "/usr/bin/remarkable", line 65, in <module>
    import remarkable
  File "/usr/lib/python3/dist-packages/remarkable/__init__.py", line 30, in <module>
    from remarkable import RemarkableWindow
  File "/usr/lib/python3/dist-packages/remarkable/RemarkableWindow.py", line 27, in <module>
    gi.require_version('WebKit', '3.0')
  File "/usr/lib64/python3.6/site-packages/gi/__init__.py", line 122, in require_version
    (namespace, version))
ValueError: Namespace WebKit not available for version 3.0
```

The package that provides WebKit 3.0 in Fedora 26 is "webkitgtk3". I don't know how many distributions the .rpm file targets, so I don't know how practical it would be to add this as a dependency to the .spec file.

**Comment by wekshi** [comment] 2017-09-05 16:03
I met the same issue in Fedora 26, work around is to using listed command.
```bash
# dnf install webkitgtk3 -y
```
add dependency +1

**Comment by Snowi95** [comment] 2017-10-13 05:19
I also had to install gtksourceview3 to get it running on Fedora 26 (With XFCE and i3).

**Comment by patdec** [comment] 2017-11-24 09:06
Hi,

it doesn't work anymore in Fedora 27. There is only webkitgtk4 now in the official repositories.

**Comment by mbloms** [comment] 2017-11-26 16:49
Duplicate of #39

**Closed** 2019-11-12 10:08 UTC
