### ISSUE TITLE
screen jitters and poor performance when typing

### ISSUE THREAD

**Issue by glithc** [jamiemcg/Remarkable#41] opened 2016-08-28 10:02 UTC
First off, I really enjoy Remarkable for it's markdown, equations and source code handling capabilities. There's this annoying problem though: when I type, Markdown preview jitters with every keystroke. Preview goes all the way to the top and then slightly above the current cursor position, which is the worst part of it all, because I don't see the rendering of what I type (I would need to scroll down to see the preview of what I typed). Whole jitter thing is coupled with not so great performance, but then again what's great performance. Let's say it lags for about a second when I hold down a key and it really shouldn't be the case given my setup. Hope all of this is helpful in some way. My operating system is Ubuntu 16.04.1 LTS 64-bit.

**Comment by jamiemcg** [comment] 2016-08-28 12:49
Duplicate of #25, #13

**Closed by jamiemcg** 2016-08-28 12:49 UTC
