### ISSUE TITLE
Add tabs support

### ISSUE THREAD

**Issue by firetrot** [jamiemcg/Remarkable#154] opened 2017-04-27 08:04 UTC
Hi!
It would be so great if you add tabs to your app (like gedit).
![image](https://cloud.githubusercontent.com/assets/2574574/25473701/1fa14a84-2b39-11e7-9f61-09d25ad16b94.png)

Now i should open several apps instances and Alt-Tab between them. With tabs it'll be convenient.
Remarkable is awesome, thanks for your job!

**Comment by Larivact** [comment] 2017-08-25 11:29
Duplicate of  #24.

**Closed** 2018-01-06 20:58 UTC

**Comment by firetrot** [comment] 2018-02-25 14:24
Delete the thread permanently, please.

**Comment by mbloms** [comment] 2018-02-26 21:31
@firetrot that's not even possible on github. Think before you post.
