### ISSUE TITLE
inline math mode ($) doesn't work but display mode ($$) works

### ISSUE THREAD

**Issue by sadid** [jamiemcg/Remarkable#176] opened 2017-07-05 06:01 UTC
here is the image
![2017-07-05-102627_1303x386_scrot](https://user-images.githubusercontent.com/3974947/27850943-012b8be0-616d-11e7-9376-adf2b42b0dad.png)

I'm using Archlinux and remarkable 1.87-1 installed from AUR.

**Comment by iamlazynic** [comment] 2017-07-21 14:51
Exactly same issue here. Using version 1.87 installed from apt on Ubuntu 17.04

**Comment by aphirst** [comment] 2017-08-02 06:23
Duplicate of https://github.com/jamiemcg/Remarkable/issues/160, temporary fix provided in comments.

**Closed** 2019-11-12 15:40 UTC
