### ISSUE TITLE
Live preview not scrolling

### ISSUE THREAD

**Issue by svartrev** [jamiemcg/Remarkable#233] opened 2018-01-10 19:02 UTC
Fresh install (v1.87) on Arch Linux:

The live preview is not scrolling at all. It can be scrolled manually, but each time you start typing, it refreshes, scrolling back to the top. Can't find any setting for it, so I assume it should automatically scroll such that the current cursor position is in view.

Any ideas?

**Comment by ToadalChaos** [comment] 2018-01-12 14:55
Duplicate of #224 ?

**Comment by svartrev** [comment] 2018-01-16 22:01
Could be. Not sure what the poster means by "flips around", but, apart from that wording, it sounds like the same issue.

**Comment by dietmar** [comment] 2018-01-26 09:03
Duplicate of #25?

**Comment by svartrev** [comment] 2018-01-26 10:34
Looks like it.

**Comment by dietmar** [comment] 2018-01-26 10:37
Please close this issue then, @svartrev.

You might want to subscribe to #25, to stay updated.

**Closed** 2018-01-26 13:34 UTC
