### ISSUE TITLE
Writing causes webview to flipp around

### ISSUE THREAD

**Issue by theScrabi** [jamiemcg/Remarkable#224] opened 2017-12-08 10:07 UTC
The webview almost never focuses on the location where I write atm.

When I write at the bottom of my document the webview flips around and scrolls to the top of the page every time I press a key.

This is very distracting.

**Comment by ToadalChaos** [comment] 2018-01-08 13:33
I agree, this needs fixing. It makes working with longer documents very difficult.

**Comment by dietmar** [comment] 2018-01-26 09:02
Duplicate of #25 ?

**Closed** 2018-01-26 09:39 UTC
