### ISSUE TITLE
Github Emoticons Not Showing in Preview

### ISSUE THREAD

**Issue by Akshar-Patel** [jamiemcg/Remarkable#188] opened 2017-08-01 05:25 UTC
Github emoticons are not showing up in the preview. It shows just text. e.g `:smile:` instead of :smile:

**Comment by timeraider4u** [comment] 2017-08-01 23:11
duplicate of #20 and #81 
+1 for anybody who is willing to fix this issue

**Closed** 2024-09-22 19:49 UTC
