### ISSUE TITLE
Feature Request: Add find and find/replace features

### ISSUE THREAD

**Issue by grumpyf0x48** [jamiemcg/Remarkable#325] opened 2019-12-24 09:14 UTC
It would be great to have find and find/replace functionality.

Not necessarily as many possibilities offered by editors and development environment, but at least basic find feature would be very helpfull.

**Comment by leonbr0wn** [comment] 2020-02-21 08:40
Duplicate of https://github.com/jamiemcg/Remarkable/issues/21

**Closed** 2024-09-22 20:27 UTC
