### ISSUE TITLE
Links don't work after exporting to PDF

### ISSUE THREAD

**Issue by manankalra** [jamiemcg/Remarkable#167] opened 2017-06-05 07:15 UTC

**Comment by lsharkey** [comment] 2017-10-08 01:56
This is my issue, too (Ubuntu, 16.04.3).  I'm generally impressed with the app, but working links in PDF exports is a must have for me.  Will have to change to a different app if this is not resolved soon.

**Comment by timeraider4u** [comment] 2017-10-08 02:08
@lsharkey Can you please provide an example which shows what is not working? For me, File->Export PDF (Styled) is working to get hypertext links working. But I am using a source-install instead of the binary debian package, so maybe it might already be fixed by some commit in the mean time.

**Comment by mbloms** [comment] 2017-10-08 22:01
Both works for me, but only if I include "http(s)". It could be your PDF viewer.

**Comment by timeraider4u** [comment] 2017-10-08 23:16
Okay, I think I can now reproduce your problem. When using the following snippet:
```
#Title
1. [Home directory](file:///home/) 
2. http://www.github.com
3. https://www.github.com
4. www.github.com
5. [Downloads folder](Downloads)
6. [Home folder](/home)
7. [Github](github.com)
8. [Github](www.github.com) 
9. [Github](http://www.github.com) 
10. [Github](https://www.github.com)

```
I can openlinks 1-4, 6 and 9-10 without problems in Okular, but for 5, 7 and 8 I get an error message in KDE5 plasma like the following `Unable to run the command specified. The file or folder /tmp/github.com does not exist`. So the _work-around_ seems to be that you explicitly set the protocol used (something that is a good idea anyway, otherwise it might be interpreted as a local file). I would, therefore, conclude that this issue is not a real bug, but rather expected behaviour.

**Comment by franc-pedro** [comment] 2020-07-30 15:43
I know this is old but if the link is internal how to do it?

**Closed** 2024-09-22 19:54 UTC
