### ISSUE TITLE
Question - is this abandonware?

### ISSUE THREAD

**Issue by thwaller** [jamiemcg/Remarkable#378] opened 2021-03-07 05:31 UTC
I was referred to try this application, but as a user of Ubuntu 20.04 it does not install... as others have pointed out. Given that it has been three years since any update, I believe this is a fair question that users should know the answer to.

While i see there have been updates, there has been none applied to the "latest version". I am looking for an alternative to Typora as it is not FOSS and the developer(s) have confirmed the intent to make it a paid solution. As an only 5 year user of FOSS and Linux, I learned quickly that unmaintained packages and softwares are generally more problems than they are worth.

**Comment by tawfiek** [comment] 2021-03-17 11:47
Duplicate of #379 
you have to install the dependencies manually first then install the app.
run  `sudo dpkg -i  remarkable_1.87_all.deb` to find out the missing deps in your environment

**Comment by mjourard** [comment] 2022-12-20 08:17
Would appreciate an answer to the original question. 180 open issues on github and the latest commit to master is more than a year and a half old.

**Comment by Ordiel** [comment] 2023-10-24 14:35
I would say this is effectively abandonware considering there have been no updates on the last 3 years, I am just wondering if anyone has a good fork of it?

For the last year or so I have switched to [Ghostwriter](https://ghostwriter.kde.org/) tho I am not sure if it is nostalgia or that this is a better editor (at least has a nicer interface) so I really want this back

**Closed** 2024-09-22 20:20 UTC
